# Generated by Django 5.0.3 on 2024-04-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип упражнения',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('difficult', models.CharField(choices=[('beginner', 'Начинающий'), ('medium', 'Средний'), ('advanced', 'Продвинутый')], max_length=255, verbose_name='Уровень сложности')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.type', verbose_name='Тип упражнения')),
            ],
            options={
                'verbose_name': 'Упражнения',
            },
        ),
    ]
