# Generated by Django 5.0.3 on 2024-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercises',
            options={'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип упражнения', 'verbose_name_plural': 'Тип упражнения'},
        ),
        migrations.AddField(
            model_name='exercises',
            name='number_of_approaches',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество подходов'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='number_of_repetitions',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество повторений'),
        ),
    ]
