# Generated by Django 5.0.3 on 2024-04-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_exercises_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время выполнения'),
        ),
    ]
