# Generated by Django 5.0.3 on 2024-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_exercises_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='difficult',
            field=models.CharField(choices=[('Начинающий', 'Начинающий'), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], max_length=255, verbose_name='Уровень сложности'),
        ),
    ]
