# Generated by Django 5.0.3 on 2024-04-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_exercises_difficult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='type',
            new_name='type_id',
        ),
    ]
