# Generated by Django 5.0.3 on 2024-04-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_type_exercises_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='type_id',
            new_name='type',
        ),
    ]
